<a href="https://colab.research.google.com/github/bhomik179/exp9.sitpune.python/blob/main/Exp9_sitpune_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Bhomik Keshi
# 25070123172
# experiment no:- 9
# Tools for eda study of numpy library

In [60]:

import numpy as np

# 1‑D array
a = np.array([1, 10, 20, 30, 40, 50, 500])
print()

# 2‑D array
b = np.array([[1, 2, 3],
               [4, 5, 6]])

print("a =", a)
print("b =")
print(b)
print()

#Shape (dimensions)
print("a.shape =", a.shape)
print("b.shape =", b.shape)
print()

#Number of dimensions
print("a.ndim =", a.ndim)
print("b.ndim =", b.ndim)
print()

#Data type of the arrays
print("a.dtype =", a.dtype)
print("b.dtype =", b.dtype)
print()

#Size of each element in bytes
print("a.itemsize =", a.itemsize)
print("b.itemsize =", b.itemsize)
print()


# Zero matrix (3×3)
e = np.zeros((3, 3))
print("zeros matrix:\n", e)
print()

u = np.eye(3)
print("identity matrix:\n", u)
print()

# Creating a range of numbers (start, stop, step)
c = np.arange(1, 10, 2)   # 1, 3, 5, 7, 9
print("arange(1,10,2) =", c)
print()
# linespace

h=np.linspace(0,10,5)
print("linspace(0,10,5) =", h)
print()


# adding adn multipying the into the same matrix
print("Adding with the number 5 in matrix\n",a+5)
print("Multiplying with the number 2 in matrix\n",b*2)
print()

mean_val = np.mean(a)

#median
median_val = np.median(a)

print("The value of the mean   is", mean_val)
print("The value of the median is\n", median_val)

print()


#maximum
max_val = np.max(a)

print("Maximum value:", max_val)
print()

# minimum
min_val = np.min(a)
print("Minimum value:", min_val)
print()

# sum
sum_val = np.sum(a)
print("Sum of all values:", sum_val)
print()















a = [  1  10  20  30  40  50 500]
b =
[[1 2 3]
 [4 5 6]]

a.shape = (7,)
b.shape = (2, 3)

a.ndim = 1
b.ndim = 2

a.dtype = int64
b.dtype = int64

a.itemsize = 8
b.itemsize = 8

zeros matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

arange(1,10,2) = [1 3 5 7 9]

linspace(0,10,5) = [ 0.   2.5  5.   7.5 10. ]

Adding with the number 5 in matrix
 [  6  15  25  35  45  55 505]
Multiplying with the number 2 in matrix
 [[ 2  4  6]
 [ 8 10 12]]

The value of the mean   is 93.0
The value of the median is
 30.0

Maximum value: 500

Minimum value: 1

Sum of all values: 651

